### ISSUE TITLE
What is the purpose of developing this tool?

### ISSUE THREAD

**Issue by koudle** [jonahwilliams/json_widget#2]
Hi Jonah Williams:
   It's an amazing tool, but I can't understand this tool. 
   How to use this tool? What's the reason you  develop this tool?  Can  it be used for hot update? 

Thank you

**Comment by AppleEducate** [comment]
No this is for generating Flutter apps from json. I’m using something similar

**Comment by rodydavis** [comment]
This is used for when you want to generate a flutter widget from a saved json schema

**Comment by jonahwilliams** [comment]
From the README:

"This is only a simple demonstration of how to write code generation in Dart"

There is no other purpose
