### ISSUE TITLE
runtime generation

### ISSUE THREAD

**Issue by ghost** [jonahwilliams/json_widget#4]
Really useful tool. I like that fact that its a data schema that matches Dart Widget tree rather than an abstraction to Markdown or HTML, etc

Please support runtime generation from the JSON schema.

Example of doing the same from HTML.
https://github.com/MartinHlavna/flutter_html_renderer.

**Comment by jonahwilliams** [comment]
This is only a simple demonstration of how to write code generation in Dart, it is not intended for runtime use - though you could use it as a starting place for one
